import { experimental_getVideoStatus as getVideoStatus, experimental_startVideo as startVideo } from 'ai';
import { BlobNotFoundError, head, issueSignedToken, presignUrl, put } from '@vercel/blob';
import { claimPaidSceneGeneration, recordPaidSceneCompletion, recordPaidSceneFailure, recordPaidSceneOperation } from './ai-ledger';
import { assembleMovie } from './movie-assembly';
import { mutateOrder, previewSceneCount, readOrder } from './orders';

const model = 'alibaba/wan-v2.6-r2v';
const PREVIEW_CONCURRENCY = 1;
const FULFILLMENT_CONCURRENCY = 1;
const PAID_VIDEO_REQUEST_INTERVAL_MS = 60_000;
const MAX_PAID_RATE_LIMIT_RETRIES = 3;
const MAX_PREVIEW_SCENE_ATTEMPTS = 2;
const MAX_PAID_SCENE_ATTEMPTS = 1;
type CompletedVideoStatus = Extract<Awaited<ReturnType<typeof getVideoStatus>>, { status: 'completed' }>;
const STALE_PAID_SCENE_MS = 15 * 60_000;
function scenePathname(orderId: string, sceneNumber: number) { return `studio/orders/${orderId}/scenes/${sceneNumber}/movie.mp4`; }
async function storedSceneExists(orderId: string, sceneNumber: number) { try { await head(scenePathname(orderId, sceneNumber)); return true; } catch (error) { if (error instanceof BlobNotFoundError) return false; throw error; } }
async function recoverStoredScene(orderId: string, sceneNumber: number) { const pathname = scenePathname(orderId, sceneNumber); if (!(await storedSceneExists(orderId, sceneNumber))) return false; await mutateOrder(orderId, (fresh) => { const scene = fresh.scenes[sceneNumber - 1]; if (!scene) return; scene.videoPathname = pathname; scene.status = 'completed'; delete scene.error; }); console.info('[DirectMovie] stored MP4 reused; zero new generation', { orderId, sceneNumber, pathname }); return true; }
export async function reconcileStalePaidScenes(orderId: string) { const order = await readOrder(orderId); if (!order || order.purchase.status !== 'paid') return; for (const scene of order.scenes.filter((scene) => scene.number > previewSceneCount())) { if (await recoverStoredScene(orderId, scene.number)) continue; const startedAt = scene.generation.startedAt ? Date.parse(scene.generation.startedAt) : 0; if (scene.status === 'submitted' && (!startedAt || Date.now() - startedAt >= STALE_PAID_SCENE_MS)) { await mutateOrder(orderId, (fresh) => { const current = fresh.scenes[scene.number - 1]; if (current?.status === 'submitted' && !current.videoPathname) { current.status = 'failed'; delete current.generation.startedAt; current.error = 'Generation result was not persisted before the recovery window expired; manual review is required before retrying.'; } }); } } }
async function assembleVerifiedStoredPreview(orderId: string) { const order = await readOrder(orderId); if (!order || order.previewMoviePathname) return; const checks = await Promise.all(Array.from({ length: previewSceneCount() }, async (_, index) => ({ number: index + 1, exists: await storedSceneExists(orderId, index + 1) }))); if (!checks.every((x) => x.exists)) return; const clips = checks.map(({ number }) => ({ number, pathname: scenePathname(orderId, number), narration: order.scenes[number - 1]?.narration ?? '' })); await mutateOrder(orderId, (fresh) => { checks.forEach(({ number }) => { const scene = fresh.scenes[number - 1]; if (!scene) return; scene.videoPathname = scenePathname(orderId, number); scene.status = 'completed'; delete scene.error; }); }); const assets = await assembleMovie(orderId, clips, 'preview'); await mutateOrder(orderId, (fresh) => { fresh.previewMoviePathname = assets.moviePathname; fresh.status = 'awaiting-payment'; }); }
async function generateScene(orderId: string, sceneNumber: number, fulfillment = false) {
 const order = await readOrder(orderId); if (!order) throw new Error('Order not found'); const scene = order.scenes[sceneNumber - 1]; if (!scene) throw new Error(`Scene ${sceneNumber} not found`);
 if (fulfillment && order.purchase.status !== 'paid') throw new Error(`blocked unpaid fulfillment scene ${sceneNumber}`); if (fulfillment && process.env.AI_PAID_GENERATION_DISABLED === 'true') throw new Error('Paid AI generation is disabled by the emergency kill switch.'); if (scene.status === 'completed' && scene.videoPathname) return; if (await recoverStoredScene(orderId, sceneNumber)) return; if (scene.status === 'submitted') return; if (fulfillment && scene.status === 'failed') throw new Error(`Scene ${sceneNumber} requires manual review before another paid generation attempt.`); if (fulfillment && scene.generation.attempts >= MAX_PAID_SCENE_ATTEMPTS) throw new Error(`Scene ${sceneNumber} reached the paid generation limit; manual review is required.`); if (!fulfillment && scene.generation.attempts >= MAX_PREVIEW_SCENE_ATTEMPTS) throw new Error(`Scene ${sceneNumber} reached ${MAX_PREVIEW_SCENE_ATTEMPTS} preview attempts; manual review required.`);
 let claimed=false; await mutateOrder(orderId,(fresh)=>{const current=fresh.scenes[sceneNumber-1];if(!current)return;if(fulfillment&&fresh.purchase.status!=='paid')return;if((current.status==='completed'&&current.videoPathname)||current.status==='submitted'||(fulfillment&&(current.status==='failed'||current.generation.attempts>=MAX_PAID_SCENE_ATTEMPTS))||(!fulfillment&&current.generation.attempts>=MAX_PREVIEW_SCENE_ATTEMPTS))return;current.status='submitted';current.generation.attempts+=1;current.generation.startedAt=new Date().toISOString();delete current.error;fresh.status=fulfillment?'fulfillment-in-progress':'preview-in-progress';claimed=true;}); if(!claimed)return;
 try {
  if(fulfillment&&!(await claimPaidSceneGeneration(orderId,sceneNumber)))return;
  const inputReferences=await Promise.all(order.subjectPhotoPathnames.slice(0,3).map(async(pathname)=>{const validUntil=Date.now()+15*60*1000;const token=await issueSignedToken({pathname,operations:['get'],validUntil});return(await presignUrl(token,{pathname,operation:'get',access:'private',validUntil,useCache:false})).presignedUrl;}));
  const prior = sceneNumber > 1 ? order.scenes[sceneNumber - 2] : undefined;
  const customerCanon = order.storyDirection.trim() || 'Use the uploaded reference subject(s) exactly; no extra typed subject facts were supplied.';
  const identityBrief=`MCS HOUSE STYLE LOCK: premium stylized 3D animated feature-film CGI; dimensional believable anatomy under gentle stylization; expressive controlled faces/eyes; soft realistic fur/hair/fabric/skin; warm cinematic lighting; natural shadows; polished global illumination; rich natural color; gentle depth of field; dimensional environments; refined storybook warmth. Same rendering language for the entire movie.
CUSTOMER CANON — HIGHEST PRIORITY: ${customerCanon}. Anything the customer explicitly states about a subject is literal canon: preserve names, number of subjects, human/animal identity, species, breed/type, coat/hair/skin/eye color, markings, age presentation, clothing/accessories and relationships. NEVER replace a specifically described subject with a generic character, different species/breed, different coloring, or different human appearance. Uploaded character1/character2/character3 references are authoritative visual evidence. HUMANS: preserve observable facial proportions, complexion, eyes, hair, age presentation, body proportions and distinctive visible features; never infer ethnicity/nationality. ANIMALS: preserve species, visually supportable breed/type, coat color/pattern, markings, muzzle, eyes, ears, tail, proportions, size and accessories.
TV-EPISODE CONTINUITY: scene ${sceneNumber} of ONE continuous movie, not a standalone clip. ${prior ? `PREVIOUS SHOT: ${prior.videoPrompt} PREVIOUS NARRATION: ${prior.narration}. Begin from that established physical/story state and continue the unfinished action naturally.` : 'This is the establishing first shot; establish the canonical subjects once and keep that exact design for the rest of the movie.'} Do not reset, recap, reintroduce, teleport or recast. Keep wardrobe/collars/accessories, props, environment/time-of-day where applicable and emotional state continuous.
LANGUAGE/VOICE: English only. One consistent neutral American English narrator identity/accent. No foreign-language speech or language switching.`;
  const started=await startVideo({model,prompt:`${identityBrief}\nCURRENT SHOT ACTION: ${scene.videoPrompt}`,inputReferences,aspectRatio:'16:9',resolution:'1280x720',duration:10,generateAudio:true,providerOptions:{alibaba:{shotType:'single'}}}); if(fulfillment)await recordPaidSceneOperation(orderId,sceneNumber,started.operation);const deadline=Date.now()+600000;let result:CompletedVideoStatus|undefined;while(Date.now()<deadline){const status=await getVideoStatus(model,{operation:started.operation});if(status.status==='completed'){result=status;break;}if(status.status==='error')throw new Error(`Wan generation failed for scene ${sceneNumber}`);await new Promise(r=>setTimeout(r,5000));}if(!result)throw new Error(`Wan generation timed out for scene ${sceneNumber}`);const video=result.videos[0];if(!video)throw new Error(`Wan returned no video for scene ${sceneNumber}`);const videoBytes=video.type==='binary'?video.data:video.type==='base64'?Uint8Array.from(Buffer.from(video.data,'base64')):new Uint8Array(await(await fetch(video.url)).arrayBuffer());const pathname=scenePathname(orderId,sceneNumber);const body=new Blob([new Uint8Array(videoBytes).buffer],{type:video.mediaType??'video/mp4'});await put(pathname,body,{access:'private',contentType:video.mediaType??'video/mp4',addRandomSuffix:false,allowOverwrite:true});await mutateOrder(orderId,(fresh)=>{const current=fresh.scenes[sceneNumber-1];if(!current)return;current.videoPathname=pathname;current.status='completed';delete current.generation.startedAt;delete current.error;});if(fulfillment)await recordPaidSceneCompletion(orderId,sceneNumber,pathname);
 } catch(error){const message=error instanceof Error?error.message:String(error);if(fulfillment)await recordPaidSceneFailure(orderId,sceneNumber,message).catch(()=>undefined);await mutateOrder(orderId,(fresh)=>{const current=fresh.scenes[sceneNumber-1];if(!current)return;current.status=fulfillment?'failed':'ready';delete current.generation.startedAt;current.error=message;});throw error;}
}
export async function runDirectPreview(orderId:string){for(let sceneNumber=1;sceneNumber<=previewSceneCount();sceneNumber+=1)await generateScene(orderId,sceneNumber);await assembleVerifiedStoredPreview(orderId);}
export async function runDirectFulfillment(orderId:string){const initial=await readOrder(orderId);if(!initial)throw new Error('Order not found');if(initial.purchase.status!=='paid')throw new Error('blocked full movie generation because payment is not confirmed');if(initial.finalMoviePathname||initial.status==='complete')return;const sceneNumbers=initial.scenes.filter(s=>s.number>6&&!(s.status==='completed'&&s.videoPathname)).map(s=>s.number);for(let index=0;index<sceneNumbers.length;index++){let retries=0;while(true){try{await generateScene(orderId,sceneNumbers[index],true);break;}catch(error){const message=error instanceof Error?error.message:String(error);if(!message.includes('429')||retries>=MAX_PAID_RATE_LIMIT_RETRIES)throw error;retries++;await new Promise(r=>setTimeout(r,PAID_VIDEO_REQUEST_INTERVAL_MS));}}if(index+1<sceneNumbers.length)await new Promise(r=>setTimeout(r,PAID_VIDEO_REQUEST_INTERVAL_MS));}const storedChecks=await Promise.all(Array.from({length:18},async(_,index)=>({number:index+1,exists:await storedSceneExists(orderId,index+1)})));const missingStored=storedChecks.filter(c=>!c.exists).map(c=>c.number);if(missingStored.length)throw new Error(`Cannot assemble final movie; stored MP4 missing for scenes: ${missingStored.join(', ')}`);await mutateOrder(orderId,(fresh)=>{storedChecks.forEach(({number})=>{const scene=fresh.scenes[number-1];if(!scene)return;scene.videoPathname=scenePathname(orderId,number);scene.status='completed';delete scene.generation.startedAt;delete scene.error;});});const order=await readOrder(orderId);if(!order)throw new Error('Order not found');const clips=order.scenes.slice(0,18).map(scene=>({number:scene.number,pathname:scene.videoPathname!,narration:scene.narration}));const assets=await assembleMovie(orderId,clips,'final');await mutateOrder(orderId,(fresh)=>{fresh.finalMoviePathname=assets.moviePathname;fresh.status='complete';});}
