'use client';

import { FormEvent, useState } from 'react';
import { upload } from '@vercel/blob/client';
import { SignInButton, UserButton, useAuth } from '@clerk/nextjs';

type Photo = { pathname: string; name: string };
type Tier = 'three' | 'five';
const products = { three: { label: '3-minute movie', price: '$49', runtime: '3 minutes', continuation: '2 minutes', scenes: 18 }, five: { label: '5-minute movie', price: '$79', runtime: '5 minutes', continuation: '4 minutes', scenes: 30 } } as const;

export function Creator() {
  const { isLoaded, isSignedIn } = useAuth();
  const [photos, setPhotos] = useState<Photo[]>([]); const [premise, setPremise] = useState(''); const [tier, setTier] = useState<Tier>('three');
  const [moods, setMoods] = useState<string[]>(['Funny']); const [referenceVideos, setReferenceVideos] = useState<string[]>([]); const [uploadPercent, setUploadPercent] = useState<number | null>(null); const [message, setMessage] = useState('Create your story plan, then render the first minute before checkout.');
  const product = products[tier];
  function toggleMood(mood: string) { setMoods((current) => current.includes(mood) ? current.filter((item) => item !== mood) : [...current, mood]); }
  async function uploadPhotos(files: FileList | null) {
    if (!files?.length) return; const selected = Array.from(files).slice(0, 5 - photos.length); if (!selected.length) return setMessage('You can add up to five reference photos.'); setMessage('Saving your reference photos privately…');
    try { const uploaded = await Promise.all(selected.map(async (file) => { const form = new FormData(); form.set('photo', file); const response = await fetch('/api/uploads/photo', { method: 'POST', body: form }); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? 'Photo upload failed.'); return data as Photo; })); setPhotos((current) => [...current, ...uploaded]); setMessage('Photos saved. Choose the mood and story direction.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Photo upload failed.'); }
  }
  async function uploadVideo(files: FileList | null) {
    const file = files?.[0]; if (!file) return; if (file.type !== 'video/mp4') return setMessage('Please select an MP4 video.'); setMessage('Uploading your movement reference securely…'); setUploadPercent(0);
    try { const init = await fetch('/api/uploads/video/init', { method: 'POST' }); const { pathname } = await init.json(); if (!init.ok || typeof pathname !== 'string') throw new Error('Unable to prepare video upload.'); const blob = await upload(pathname, file, { access: 'private', handleUploadUrl: '/api/uploads/video', onUploadProgress: ({ percentage }) => setUploadPercent(Math.round(percentage)) }); setReferenceVideos((current) => [...current, blob.pathname]); setMessage('Movement reference saved privately.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Video upload failed.'); } finally { setUploadPercent(null); }
  }
  async function createStory(event: FormEvent) {
    event.preventDefault(); setMessage(`Writing your complete ${product.runtime} story plan…`);
    try { const storyResponse = await fetch('/api/story', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ premise: premise.trim() || 'Create an original story for me.', subjectPhotoPathnames: photos.map((photo) => photo.pathname), tier, moods }) }); const storyData = await storyResponse.json(); if (!storyResponse.ok) throw new Error(storyData.error ?? 'Story creation failed.'); const orderResponse = await fetch('/api/orders', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ ...storyData.story, tier, moods, subjectPhotoPathnames: photos.map((photo) => photo.pathname) }) }); const orderData = await orderResponse.json(); if (!orderResponse.ok) throw new Error(orderData.error ?? 'Order setup failed.'); setMessage(`Your ${product.runtime} story is planned as ${product.scenes} connected scenes. Render scenes 1–6 to create the real 60-second preview (order ${orderData.order.id}).`); } catch (error) { setMessage(error instanceof Error ? error.message : 'Story creation failed.'); }
  }
  return <section className="creator"><div className="creator-header"><div><p className="eyebrow">Your private movie studio</p><h2>Make them the star</h2></div>{isLoaded && (isSignedIn ? <UserButton /> : <SignInButton mode="modal"><button type="button">Create a free account</button></SignInButton>)}</div><p className="creator-lede">Choose a complete movie length first. Your first 60 seconds are the real opening of that same planned story.</p><div className="photo-upload"><label>1. Choose your movie package<select value={tier} onChange={(event) => setTier(event.target.value as Tier)}><option value="three">$49 — 3-minute movie + matching storybook</option><option value="five">$79 — 5-minute movie + matching storybook</option></select></label><p>{product.runtime} of intentional story, with a 60-second preview and {product.continuation} continuing after payment.</p></div><div className="photo-upload"><label>2. Upload your star<input type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={(event) => void uploadPhotos(event.target.files)} /></label><p>Add 1–5 clear photos of the child, pet, or loved one. They stay private.</p>{photos.length > 0 && <ul>{photos.map((photo) => <li key={photo.pathname}>{photo.name}</li>)}</ul>}</div><div className="photo-upload"><label>Optional: add a movement reference video<input type="file" accept="video/mp4" onChange={(event) => void uploadVideo(event.target.files)} /></label><p>Upload one MP4 up to 200 MB to guide natural movement. {uploadPercent !== null ? `Uploading ${uploadPercent}%…` : referenceVideos.length ? 'Movement reference saved.' : ''}</p></div><form onSubmit={createStory}><label>3. Choose the mood</label><div className="moods">{['Funny', 'Dramatic', 'Fantasy', 'Sci-fi', 'Scary', 'Dark humor'].map((mood) => <label key={mood}><input type="checkbox" checked={moods.includes(mood)} onChange={() => toggleMood(mood)} /> {mood}</label>)}</div><label>4. Tell us their adventure<textarea value={premise} onChange={(event) => setPremise(event.target.value)} placeholder="Remi goes to the rodeo" /></label><button type="submit" disabled={!photos.length || !moods.length}>Create my 60-second preview plan</button></form><div className="movie-promise"><span>One connected story package</span><b>{product.runtime} total</b><span>Free preview: the first 60 seconds</span><strong>{product.price} unlocks the same story&apos;s remaining movie and matching {product.scenes}-page Storybook</strong></div>{isLoaded && <p className="status" role="status">{message}</p>}</section>;
}
