'use client';

import { FormEvent, useEffect, useState } from 'react';
import { SignInButton, useAuth } from '@clerk/nextjs';
type Photo = { pathname: string; name: string }; type Tier = 'three' | 'five'; type Scene = { number: number; status: string; videoPathname?: string }; type Order = { id: string; title: string; scenes: Scene[]; status: string; continuationStatus: string; purchase: { status: string } };
const products = { three: { price: '$49', label: '3-minute movie', scenes: 18 }, five: { price: '$79', label: '5-minute movie', scenes: 30 } } as const;
export function Creator() {
  const { isSignedIn } = useAuth(); const [photos, setPhotos] = useState<Photo[]>([]); const [idea, setIdea] = useState(''); const [mood, setMood] = useState('Funny'); const [tier, setTier] = useState<Tier>('three'); const [order, setOrder] = useState<Order | null>(null); const [working, setWorking] = useState(false); const [needsAccount, setNeedsAccount] = useState(false); const [message, setMessage] = useState('Upload a photo. We turn it into a complete animated story.');
  useEffect(() => {
    const params = new URLSearchParams(window.location.search); const id = params.get('order') || window.localStorage.getItem('mcs-order-id');
    if (!id) return; void refreshOrder(id);
    if (params.get('checkout') !== 'success') return;
    const timer = window.setInterval(() => void refreshOrder(id), 3000);
    return () => window.clearInterval(timer);
  }, []);
  async function refreshOrder(id: string) { const response = await fetch(`/api/orders/${id}`); if (response.ok) { const data = await response.json(); setOrder(data.order); return data.order as Order; } return null; }
  async function uploadPhotos(files: FileList | null) { if (!files?.length) return; const selected = Array.from(files).slice(0, 3 - photos.length); if (!selected.length) return setMessage('You can add up to three photos.'); setMessage('Saving your photo privately…'); try { const upload = async (file: File) => { const form = new FormData(); form.set('photo', file); const response = await fetch('/api/uploads/photo', { method: 'POST', body: form }); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? 'Photo upload failed.'); return data as Photo; }; const first = await upload(selected[0]); const uploaded = [first, ...await Promise.all(selected.slice(1).map(upload))]; setPhotos((current) => [...current, ...uploaded]); setMessage('Perfect. Tell us a little—or let us make the magic.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Photo upload failed.'); } }
  async function waitForScenes(id: string, numbers: number[]) { for (;;) { const results = await Promise.all(numbers.map(async (number) => { const response = await fetch(`/api/orders/${id}/scenes/${number}`); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? `Scene ${number} failed.`); return data.scene as Scene; })); setOrder((current) => current ? { ...current, scenes: current.scenes.map((scene) => results.find((result) => result.number === scene.number) ?? scene) } : current); if (results.some((scene) => scene.status === 'failed')) throw new Error('A scene failed to generate. Try again later.'); if (results.every((scene) => scene.status === 'completed')) return; await new Promise((resolve) => setTimeout(resolve, 6000)); } }
  async function runScenes(current: Order, numbers: number[], label: string) { if (!numbers.length) return; setWorking(true); setMessage(`Starting ${label}…`); try { await Promise.all(numbers.map(async (number) => { const response = await fetch(`/api/orders/${current.id}/scenes/${number}/start`, { method: 'POST' }); if (!response.ok && response.status !== 409) { const data = await response.json(); throw new Error(data.error ?? 'Unable to start movie production.'); } })); await waitForScenes(current.id, numbers); const updated = await refreshOrder(current.id); setMessage(numbers[0] === 1 ? 'Your 60-second opening preview is ready. Choose how long you want the full story to be.' : `Your ${updated?.scenes.length === 30 ? '5' : '3'}-minute story scenes are ready.`); } catch (error) { setMessage(error instanceof Error ? error.message : 'Movie production failed.'); } finally { setWorking(false); } }
  async function createPreview(event: FormEvent) { event.preventDefault(); setWorking(true); setMessage('Creating their magical 60-second opening…'); try { const response = await fetch('/api/story', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ premise: idea, subjectPhotoPathnames: photos.map((photo) => photo.pathname), moods: [mood] }) }); const story = await response.json(); if (!response.ok) throw new Error(story.error ?? 'Story creation failed.'); const created = await fetch('/api/orders', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ ...story.story, storyDirection: idea, moods: [mood], subjectPhotoPathnames: photos.map((photo) => photo.pathname) }) }); const data = await created.json(); if (!created.ok) throw new Error(data.error ?? 'Order setup failed.'); window.localStorage.setItem('mcs-order-id', data.order.id); setOrder(data.order); setWorking(false); await runScenes(data.order, [1, 2, 3, 4, 5, 6], 'your real 60-second preview'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Story creation failed.'); setWorking(false); } }
  async function checkout() { if (!order) return; setWorking(true); setNeedsAccount(false); try { const response = await fetch('/api/orders/checkout', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ orderId: order.id, tier }) }); const data = await response.json(); if (data.needsAccount) { setNeedsAccount(true); throw new Error('Create your free account to save this story, then unlock it.'); } if (!response.ok) throw new Error(data.error ?? 'Checkout could not start.'); window.location.assign(data.checkoutUrl); } catch (error) { setMessage(error instanceof Error ? error.message : 'Checkout could not start.'); setWorking(false); } }
  async function continueMovie() { if (!order) return; setWorking(true); setMessage('Confirming your purchase and expanding the same story…'); try { let current = await refreshOrder(order.id); if (!current || current.purchase.status !== 'paid') throw new Error('Payment is still confirming. Try again in a moment.'); if (current.continuationStatus !== 'planned') { const response = await fetch(`/api/orders/${current.id}/continuation`, { method: 'POST' }); const data = await response.json(); if (!response.ok && response.status !== 409) throw new Error(data.error ?? 'Continuation planning failed.'); current = data.order ?? await refreshOrder(current.id); } if (!current) throw new Error('Order unavailable.'); await runScenes(current, current.scenes.filter((scene) => scene.number > 6 && scene.status === 'ready').map((scene) => scene.number), 'the rest of your movie'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Unable to continue your movie.'); setWorking(false); } }
  useEffect(() => {
    if (!order || order.purchase.status !== 'paid' || order.continuationStatus !== 'ready' || working) return;
    void continueMovie();
  }, [order?.id, order?.purchase.status, order?.continuationStatus]);
  const previewReady = order?.status === 'awaiting-payment';
  return <section className="creator"><div className="creator-header"><div><p className="eyebrow">Your private movie studio</p><h2>Make them the star</h2></div></div><p className="creator-lede">No screenplay. No account yet. Upload a photo and we make the story.</p>{!order && <form onSubmit={createPreview}><div className="photo-upload"><label>1. Upload their photo<input type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={(event) => void uploadPhotos(event.target.files)} /></label><p>One photo is enough. Add up to three if you want.</p>{photos.length > 0 && <ul>{photos.map((photo) => <li key={photo.pathname}>{photo.name}</li>)}</ul>}</div><label>2. Pick a vibe<select value={mood} onChange={(event) => setMood(event.target.value)}>{['Funny', 'Fantasy', 'Adventure', 'Dramatic', 'Sci-fi', 'Scary'].map((item) => <option key={item}>{item}</option>)}</select></label><label>Optional: what should happen?<textarea value={idea} onChange={(event) => setIdea(event.target.value)} placeholder="Tiffani and her dog Remi go on a Halloween adventure—or leave blank and we’ll make it up." /></label><button type="submit" disabled={!photos.length || working}>{idea.trim() ? 'Create their movie preview' : 'Create a story for me'}</button></form>}{order && <div className="order-panel"><b>{order.title}</b><p>Order status: {order.status.replaceAll('-', ' ')}</p><div className="preview-grid">{order.scenes.filter((scene) => scene.number <= 6 && scene.videoPathname).map((scene) => <video key={scene.number} controls src={`/api/orders/${order.id}/scenes/${scene.number}/video`} />)}</div>{previewReady && <><p>Love the preview? Choose the full movie length.</p><select value={tier} onChange={(event) => setTier(event.target.value as Tier)}><option value="three">$49 — 3-minute movie + Storybook</option><option value="five">$79 — 5-minute movie + Storybook</option></select>{needsAccount && !isSignedIn ? <SignInButton mode="modal"><button>Create your free account to unlock</button></SignInButton> : <button onClick={() => void checkout()} disabled={working}>Unlock the {products[tier].label}</button>}</>}{order.purchase.status === 'checkout-created' && <button onClick={() => void continueMovie()} disabled={working}>Continue my movie</button>}{order.purchase.status === 'paid' && order.continuationStatus !== 'planned' && <button onClick={() => void continueMovie()} disabled={working}>Continue my movie</button>}</div>}<div className="movie-promise"><span>One photo. One real story.</span><b>Watch the first 60 seconds free</b><span>Choose the full length only after you love it</span><strong>$49 for 3 minutes or $79 for 5 minutes, plus the matching Storybook</strong></div><p className="status" role="status">{message}</p></section>;
}
