import { Creator } from './creator';
import { OneMinuteCopy } from './one-minute-copy';
import './storefront-template.css';

const steps=[['↑','1. Upload','Add photos and pick your vibe'],['✦','2. We Create','AI crafts your custom animated story'],['1m','3. Preview','Watch your first 1 minute free'],['▣','4. Checkout','Secure payment with Stripe'],['★','5. We Finish','We complete your full movie'],['↓','6. You Enjoy','Download and keep your movie']];
const examples=[['/brand/example-child-dog.jpg','People + pets'],['/brand/example-girl-space.jpg','Sci-fi adventures'],['/brand/example-family.jpg','Family stories'],['/brand/example-dog-beach.jpg','Pet adventures'],['/brand/example-fantasy.jpg','Fantasy worlds']];
export default function Home(){return <main className="template-page"><OneMinuteCopy/>
<nav className="template-nav"><div className="template-shell"><a className="template-brand" href="#top"><img src="/brand/mcs-circle-logo.jpg" alt="Main Character Studios by Tiffani"/><span className="template-brand-copy"><strong>Main Character Studios</strong><em>by Tiffani</em><small>WHERE YOUR STORY BECOMES A MOVIE</small></span></a><div className="template-links"><a href="#top">Home</a><a href="#how">How It Works</a><a href="#examples">Examples</a><a href="#pricing">Pricing</a><a href="#create">My Orders</a><span className="coming">✦ AI-SELF COMING SOON</span></div></div></nav>
<section className="template-hero" id="top"><div className="template-shell hero-grid"><div><p className="hero-kicker">Photos In. Movie Magic Out.</p><h1>Turn Your Photos Into Unforgettable <i>Animated Stories</i></h1><p className="hero-sub">Cinematic. Emotional. One-of-a-kind.<br/>Starring you, your loved ones, or your pets.</p><div className="feature-row"><div className="feature"><span className="feature-icon">▦</span><span><b>AI-Powered</b>Storytelling + animation</span></div><div className="feature"><span className="feature-icon">◷</span><span><b>3-Minute Movie</b>$49</span></div><div className="feature"><span className="feature-icon">∞</span><span><b>Come Back Anytime</b>Buy as many different stories as you want</span></div></div><div className="cta-row"><a className="gold-cta" href="#create">✦ Start Your Story</a><a className="purple-cta" href="#examples">See Examples</a></div><p className="preview-note">Get 1 free 1-minute preview • No payment required</p></div><div className="hero-art"><img src="/brand/mcs-circle-logo.jpg" alt="Main Character Studios by Tiffani circular film logo"/></div></div></section>
<section className="how" id="how"><div className="template-shell"><h2 className="section-heading">How It Works</h2><p className="section-sub">It’s simple. You provide the moments — we turn them into movie magic.</p><div className="steps-flow">{steps.map(([icon,title,text])=><div className="flow-step" key={title}><div className="flow-icon">{icon}</div><strong>{title}</strong><span>{text}</span></div>)}</div></div></section>
<section className="pricing" id="pricing"><div className="template-shell"><h2 className="section-heading">Choose Your Story Length</h2><p className="section-sub">Your Story. Your Way.</p><div className="price-grid"><article className="price-card"><div><span className="price">$49</span><h3>3-Minute Movie</h3></div><ul><li>Full 3-minute cinematic animated movie</li><li>1-minute free preview</li><li>Download and keep your finished movie</li><li>Order another story whenever you want</li></ul><a className="purple-cta" href="#create">Choose 3 Minutes</a></article><article className="price-card featured"><span className="badge">COMING SOON</span><div><span className="price">$79</span><h3>5-Minute Movie</h3></div><ul><li>Full 5-minute cinematic animated movie</li><li>1-minute free preview</li><li>Longer adventures and deeper stories</li></ul><p className="soon">$79 • Coming Soon</p></article></div></div></section>
<section className="examples" id="examples"><div className="template-shell"><h2 className="section-heading">See the Magic</h2><p className="section-sub">A few visual examples of the kinds of stories you can create.</p><div className="still-grid">{examples.map(([src,label])=><figure className="still-card" key={label}><img src={src} alt={`${label} animated story example`}/><figcaption>{label}</figcaption></figure>)}</div></div></section>
<section className="repeat"><div className="template-shell repeat-inner"><div><p className="hero-kicker">A new story whenever you want one.</p><h2>One purchase does not limit you to one story.</h2></div><p>Come back anytime and create another movie. Make as many personalized stories as you want—for different people, pets, adventures, birthdays, holidays, gifts, or just because.</p></div></section>
<section className="studio-wrap" id="create"><div className="template-shell"><h2 className="section-heading">Ready to make them the main character?</h2><p className="section-sub">Create one today, then come back whenever inspiration strikes.</p><Creator/></div></section>
<footer className="template-footer"><div className="template-shell"><strong>Everyone deserves a story where they’re the star.</strong><p>Main Character Studios by Tiffani • Personalized cinematic animated stories</p></div></footer></main>}
