import { Creator } from './creator';
import './fresh-storefront.css';

const demos=[
['Fantasy Worlds','https://raw.githubusercontent.com/debeaux13-cloud/scaling-palm-tree/main/bb2d76adcbaed338e7f9c7049a2a874c76e4ef2e842b6407d0cefd8dea23db44.MP4'],
['Pet Adventures','https://raw.githubusercontent.com/debeaux13-cloud/scaling-palm-tree/main/92c188437820364e6cbd74dc26272c64092da7841d3ab6b82b511dac740aa7da.MP4'],
['Family Adventures','https://raw.githubusercontent.com/debeaux13-cloud/scaling-palm-tree/main/f080f5f16d6ab3340e077d9279ec37798ed60653b0015801afdc9ad2ecb4c0e8.MP4'],
['Sci-Fi Stories','https://raw.githubusercontent.com/debeaux13-cloud/scaling-palm-tree/main/29f2ba617ca782724186fc33b14c5270579793f4d16ed7f27337fcfa40bf20b8.MP4'],
['Special Moments','https://raw.githubusercontent.com/debeaux13-cloud/scaling-palm-tree/main/f6eb27ddf0095727546f2458b95b414bfd131f7992c15efeff9babcbf8334a48.MP4']];

export default function Home(){return <main className="cinema" id="top">
<header className="cinema-nav"><a className="cinema-brand" href="#top"><span className="brand-mark">M</span><span><b>Main Character Studios</b><i>by Tiffani</i></span></a><nav><a href="#films">Examples</a><a href="#how">How it works</a><a href="#pricing">Pricing</a><a href="#studio" className="nav-cta">Create your story</a></nav></header>
<section className="hero"><div className="hero-art"/><div className="hero-shade"/><div className="hero-copy"><span className="eyebrow">PERSONALIZED CINEMATIC STORIES</span><h1>Their photo.<br/><em>Their adventure.</em><br/>Their story.</h1><p>Turn the people and pets you love into a personalized cinematic modern 3D computer-animated story — built as one connected adventure from beginning to end.</p><div className="hero-actions"><a href="#studio">CREATE A FREE PREVIEW</a><a href="#films" className="ghost">WATCH EXAMPLES</a></div><small>60-second preview free · 3-minute story $49 · make as many stories as you want</small></div></section>
<section className="promise"><span>ONE PHOTO CAN START A WHOLE WORLD</span><p>Family adventures · Pet chaos · Fantasy · Sci-fi · Special moments</p></section>
<section className="films" id="films"><div className="section-head"><span>THE MAIN CHARACTER LOOK</span><h2>Stories should <em>look like stories.</em></h2><p>Warm cinematic light, dimensional characters, expressive faces and rich animated worlds. These are the visual directions your personalized 3D animated story is built around.</p></div><div className="film-grid">{demos.map(([name,src])=><article className="film-card" key={name}><video src={src} controls muted playsInline preload="metadata"/><div><strong>{name}</strong><span>Explore this world</span></div></article>)}</div></section>
<section className="how" id="how"><div className="how-copy"><span>FROM CAMERA ROLL TO CINEMATIC STORY</span><h2>You bring the face.<br/><em>We build the world.</em></h2><p>No screenplay required. Upload a favorite photo, choose the mood, and tell us the adventure — or leave it to us.</p></div><div className="steps"><article><b>01</b><h3>Upload</h3><p>Add the person, pet, or crew who should star.</p></article><article><b>02</b><h3>Create</h3><p>We build a cohesive modern 3D computer-animated story around them.</p></article><article><b>03</b><h3>Preview</h3><p>Watch the first 60 seconds free.</p></article><article><b>04</b><h3>Unlock</h3><p>Love it? Unlock and download the rest of the same cohesive story.</p></article></div></section>
<section className="pricing" id="pricing"><div className="pricing-copy"><span>YOUR STORY. YOUR WAY.</span><h2>Same cinematic experience.<br/><em>Choose your story length.</em></h2><p>Both lengths are the same personalized cinematic modern 3D computer-animation experience. The only product difference is how long your story runs. Make as many different stories as you want.</p></div><article className="price live"><span>AVAILABLE NOW</span><div><b>$49</b><h3>3-Minute Personalized Cinematic 3D Animated Story</h3></div><ul><li>60-second preview first</li><li>One cohesive story from beginning to end</li><li>Finished MP4 to keep</li></ul><a href="#studio">START FREE</a></article><article className="price soon"><span>COMING SOON</span><div><b>$79</b><h3>5-Minute Personalized Cinematic 3D Animated Story</h3></div><p>The exact same personalized cinematic modern 3D computer-animation experience as the $49 story, extended to five minutes.</p></article></section>
<section className="studio" id="studio"><div className="studio-title"><span>LIGHTS. CAMERA. YOU.</span><h2>Make them the main character.</h2><p>Start with a photo. Your first minute is free.</p></div><Creator/></section>
<footer><div className="footer-brand"><b>Main Character Studios</b><i>by Tiffani</i></div><p>Everyone deserves a story where they’re the star.</p></footer>
</main>}