import { Creator } from './creator';
import './fresh-storefront.css';

const art=['https://raw.githubusercontent.com/debeaux13-cloud/scaling-palm-tree/main/1788448191055.png','https://raw.githubusercontent.com/debeaux13-cloud/scaling-palm-tree/main/4CDFB764-5E34-47D7-944B-65BD8ED0BA5C.png','https://raw.githubusercontent.com/debeaux13-cloud/scaling-palm-tree/main/Untitled%20design.png'];
const demos=[['Fantasy Worlds','https://raw.githubusercontent.com/debeaux13-cloud/scaling-palm-tree/main/bb2d76adcbaed338e7f9c7049a2a874c76e4ef2e842b6407d0cefd8dea23db44.MP4'],['Pet Adventures','https://raw.githubusercontent.com/debeaux13-cloud/scaling-palm-tree/main/92c188437820364e6cbd74dc26272c64092da7841d3ab6b82b511dac740aa7da.MP4'],['Family Adventures','https://raw.githubusercontent.com/debeaux13-cloud/scaling-palm-tree/main/f080f5f16d6ab3340e077d9279ec37798ed60653b0015801afdc9ad2ecb4c0e8.MP4']];
export default function Home(){return <main className="storybook" id="top"><header className="story-nav"><a className="story-brand" href="#top"><span className="new-logo"><i>✦</i><b>M</b></span><span className="brand-words"><strong>MAIN CHARACTER</strong><em>STUDIOS</em><small>by Tiffani</small></span></a><nav><a href="#worlds">Stories</a><a href="#films">Watch</a><a href="#pricing">Pricing</a><a href="#studio" className="nav-cta">CREATE YOUR STORY ✦</a></nav></header>
<section className="hero" style={{'--hero':`url(${art[0]})`} as React.CSSProperties}><div className="hero-art"/><div className="hero-copy"><span className="eyebrow">PERSONALIZED 3D ANIMATED STORIES</span><h1>Make someone you love the <em>main character.</em></h1><p>Turn your favorite people and pets into the stars of a cinematic animated adventure made just for them.</p><div className="hero-actions"><a href="#studio">CREATE MY FREE PREVIEW ✦</a><a href="#films" className="ghost">WATCH STORIES</a></div><small>No account needed to start • Free 60-second preview</small></div><div className="hero-stamp"><span>A STORY</span><b>MADE FOR</b><strong>YOU</strong></div></section>
<section className="magic-strip"><span>YOUR PHOTO</span><i>✦</i><span>YOUR IDEA</span><i>✦</i><span>YOUR ADVENTURE</span></section>
<section className="worlds" id="worlds"><div className="world-copy"><span>ANYONE CAN BE THE STAR</span><h2>Put them somewhere <em>extraordinary.</em></h2><p>Send the family into space. Give the dog a kingdom. Turn a birthday into an adventure. Make a favorite memory magical.</p></div><div className="world-collage"><img src={art[1]} alt="Cinematic animated adventure"/><img src={art[2]} alt="Personalized animated story world"/></div></section>
<section className="films" id="films"><div className="section-head"><span>WATCH THE POSSIBILITIES</span><h2>Big worlds.<br/><em>Familiar faces.</em></h2><p>Modern 3D animation with expressive characters, rich environments and cinematic lighting.</p></div><div className="film-grid">{demos.map(([name,src])=><article className="film-card" key={name}><video src={src} controls muted playsInline preload="metadata"/><div><strong>{name}</strong><span>PERSONALIZED 3D ANIMATED STORY</span></div></article>)}</div></section>
<section className="how"><span className="eyebrow">HOW IT WORKS</span><h2>Your idea becomes their <em>adventure.</em></h2><div className="steps"><article><b>01</b><h3>Upload a photo</h3><p>Choose a person, pet, family or crew.</p></article><article><b>02</b><h3>Pick the vibe</h3><p>Add a simple idea or let us create one for you.</p></article><article><b>03</b><h3>See your preview</h3><p>Watch the first 60 seconds free, then choose your story length.</p></article></div></section>
<section className="pricing" id="pricing"><div className="pricing-copy"><span>CHOOSE YOUR STORY</span><h2>Three minutes or five.<br/><em>Your world, your way.</em></h2><p>Personalized cinematic modern 3D computer animation starring your people and pets.</p></div><article className="price live"><span>3-MINUTE STORY</span><b>$49</b><h3>3-Minute Personalized Story</h3><ul><li>Free 60-second preview</li><li>3-minute animated story</li><li>Matching storybook PDF</li><li>Finished video to keep</li></ul><a href="#studio">START FREE ✦</a></article><article className="price live"><span>5-MINUTE STORY</span><b>$79</b><h3>5-Minute Personalized Story</h3><ul><li>Free 60-second preview</li><li>5-minute animated story</li><li>Matching storybook PDF</li><li>Finished video to keep</li></ul></article></section>
<section className="studio" id="studio"><div className="studio-title"><span>✦ CREATE YOUR STORY ✦</span><h2>Who gets to be the <em>main character?</em></h2><p>Upload a photo and give us the idea.</p></div><Creator/></section><footer><a className="story-brand" href="#top"><span className="new-logo"><i>✦</i><b>M</b></span><span className="brand-words"><strong>MAIN CHARACTER</strong><em>STUDIOS</em><small>by Tiffani</small></span></a><p>Personalized animated stories starring the people and pets you love. ✦</p></footer></main>}