import { generateObject } from 'ai';
import { z } from 'zod';
import { NextResponse } from 'next/server';
import { getOwner } from '../../../lib/owner';
const storySchema = z.object({ title: z.string().min(1), scenes: z.array(z.object({ narration: z.string().min(1), videoPrompt: z.string().min(1) })).length(18) });
const HOUSE_STYLE = `MAIN CHARACTER STUDIOS HOUSE STYLE: premium stylized 3D animated feature-film CGI. Characters are dimensional and appealing with believable anatomy beneath gentle stylization, expressive but controlled eyes and faces, soft realistic fur/hair/fabric/skin materials, warm cinematic feature-film lighting, natural shadows, polished global illumination, rich natural color, gentle depth of field, dimensional environments, clean shapes, and a refined storybook warmth. Keep this exact rendering language throughout all 18 scenes. Do not drift into photorealism, flat illustration, anime, 2D/cartoon line art, plastic toy rendering, or a different character-design style.`;
const CONTINUITY = `CONTINUITY: Write all 18 scenes as consecutive shots from ONE movie, not 18 standalone mini-films. Each scene must inherit established character appearance, wardrobe/accessories, proportions, environment continuity when applicable, emotional state, story position, and visual language from the previous scene. Scene action should enter from what just happened and leave a clear handoff into the next scene. Do not repeatedly reintroduce the characters or reset the story.`;
const LANGUAGE = `LANGUAGE LOCK: English only. Write every narration line and any spoken dialogue in natural English. Do not introduce foreign-language words, dialogue, singing, narration, or language switching. Do not infer language, nationality, ethnicity, or accent from a person's appearance, name, photograph, location, or story setting.`;
export async function POST(request: Request) {
  const { ownerId } = await getOwner(); const { premise, subjectPhotoPathnames = [], moods = [] } = await request.json();
  if (!Array.isArray(subjectPhotoPathnames) || !Array.isArray(moods) || typeof premise !== 'string') return NextResponse.json({ error: 'Photo references, mood, and story direction are required.' }, { status: 400 });
  if (subjectPhotoPathnames.length < 1 || subjectPhotoPathnames.length > 3) return NextResponse.json({ error: 'Upload one to three reference photos.' }, { status: 400 });
  if (subjectPhotoPathnames.some((pathname: unknown) => typeof pathname !== 'string' || !pathname.startsWith(`studio/owners/${ownerId}/references/`))) return NextResponse.json({ error: 'Photo references must belong to this preview.' }, { status: 403 });
  const { object } = await generateObject({ model: 'openai/gpt-5.4', schema: storySchema, prompt: `Write one complete connected 18-scene, 180-second animated movie. ${HOUSE_STYLE} ${CONTINUITY} ${LANGUAGE} The customer's direction is the story brief: follow it faithfully and make the full story yourself without asking the customer to edit, choose plot points, or extend it later. Mood: ${moods.join(', ') || 'family adventure'}. Customer direction: ${premise.trim() || 'Create an original, joyful adventure from the uploaded subject.'}. Build a real beginning, escalating middle, climax, and satisfying ending across exactly 18 connected 10-second scenes. Scenes 1-6 must also work as an irresistible 60-second free preview while remaining the true opening of the same 3-minute story; scenes 7-18 continue that already-planned story after purchase. Preserve the reference subjects' observable appearance and distinctive visible features throughout without assigning or inferring ethnicity or nationality. Every scene must contain meaningful physical action, expressive movement, camera direction, and concise English narration that leaves room for visual storytelling. Each videoPrompt must explicitly preserve the established MCS house style and continuity with the preceding scene. Match the requested mood strongly. Do not add scene labels.` });
  return NextResponse.json({ story: object });
}
