import { generateObject } from 'ai';
import { z } from 'zod';
import { NextResponse } from 'next/server';
import { getOwner } from '../../../lib/owner';
const storySchema = z.object({ title: z.string().min(1), scenes: z.array(z.object({ narration: z.string().min(1), videoPrompt: z.string().min(1) })).length(18) });
const HOUSE_STYLE = `MAIN CHARACTER STUDIOS HOUSE STYLE: premium stylized 3D cinematic animated feature-film CGI. Dimensional appealing characters with believable anatomy beneath gentle stylization, expressive but controlled eyes/faces, soft realistic fur/hair/fabric/skin materials, cinematic feature-film lighting, natural shadows, polished global illumination, rich natural color, gentle depth of field, dimensional environments, clean shapes, refined storybook warmth. ONE rendering language for the whole movie. Never drift into photorealism, flat illustration, anime, 2D line art, plastic-toy rendering, or a different character-design style.`;
const CONTINUITY = `CINEMATIC CONTINUOUS FILM: Create ONE cohesive cinematic animated movie with the visual and narrative continuity of a professionally edited TV episode or short film. The 10-second generation boundaries are invisible production segments only; the customer must experience a continuous 3-minute film. Never treat segments as separate clips, mini-films, vignettes, trailers, montages, recaps, fresh establishing scenes, or independent shorts. Segment N+1 begins naturally from Segment N's ending action and preserves the established characters, design, wardrobe/collars/accessories, camera geography, environment, lighting/time of day, props, emotional state and story momentum. Carry unfinished movement and action across boundaries when appropriate. Do not reset, reintroduce, recap, teleport, redesign or independently recast subjects. Every videoPrompt must explicitly state the incoming continuity from the preceding segment and the outgoing action that flows into the next segment.`;
const LANGUAGE = `LANGUAGE LOCK: English only by default. Every narration line and any spoken dialogue/singing containing words is natural English. Never introduce another language or infer language, nationality, ethnicity or accent from appearance, name, photograph, location or setting.`;
export async function POST(request: Request) {
  const { ownerId } = await getOwner(); const { premise, subjectPhotoPathnames = [], moods = [] } = await request.json();
  if (!Array.isArray(subjectPhotoPathnames) || !Array.isArray(moods) || typeof premise !== 'string') return NextResponse.json({ error: 'Photo references, mood, and story direction are required.' }, { status: 400 });
  if (subjectPhotoPathnames.length < 1 || subjectPhotoPathnames.length > 3) return NextResponse.json({ error: 'Upload one to three reference photos.' }, { status: 400 });
  if (subjectPhotoPathnames.some((pathname: unknown) => typeof pathname !== 'string' || !pathname.startsWith(`studio/owners/${ownerId}/references/`))) return NextResponse.json({ error: 'Photo references must belong to this preview.' }, { status: 403 });
  const customerCanon = premise.trim();
  const { object } = await generateObject({ model: 'openai/gpt-5.4', schema: storySchema, prompt: `Write ONE continuous cinematic 3-minute animated film in exactly 18 invisible production segments. ${HOUSE_STYLE} ${CONTINUITY} ${LANGUAGE}
CUSTOMER CANON — HIGHEST PRIORITY SUBJECT FACTS: ${customerCanon || 'No extra typed subject facts; use the uploaded reference subject(s) as authoritative.'}
Anything the customer explicitly states about a subject—name, human/animal identity, species, breed/type, coat/hair/skin/eye color, markings, age presentation, clothing, relationship or other visible/identity detail—is CANON and must be repeated accurately in every relevant segment prompt. Never replace a specifically described subject with a generic character, different breed/species, different coloring, different human appearance or different number of subjects. Uploaded photos are authoritative visual references and supplement the customer's words. Do not infer ethnicity or nationality.
Mood: ${moods.join(', ') || 'family adventure'}. Follow the customer's requested story faithfully; when they leave the story blank, invent the plot while preserving the reference subjects exactly. Build a cinematic beginning, escalating middle, climax and satisfying ending. Segments 1-6 form the 1-minute free preview and are the actual opening of this same 3-minute film; segments 7-18 continue that exact film after purchase. Every segment advances the same plot with meaningful physical action, intentional camera movement/composition and concise English narration. No segment may behave like a restart. Every videoPrompt must restate canonical subject identity/details relevant to that shot, the exact incoming continuity from the prior segment, and the outgoing motion/story beat that carries into the next. Do not add segment labels.` });
  return NextResponse.json({ story: object });
}
