import { generateObject } from 'ai';
import { z } from 'zod';
import { NextResponse } from 'next/server';
import { getOwner } from '../../../lib/owner';
const storySchema = z.object({ title: z.string().min(1), scenes: z.array(z.object({ narration: z.string().min(1), videoPrompt: z.string().min(1) })).length(18) });
const HOUSE_STYLE = `MAIN CHARACTER STUDIOS HOUSE STYLE: premium stylized 3D animated feature-film CGI. Dimensional appealing characters with believable anatomy beneath gentle stylization, expressive but controlled eyes/faces, soft realistic fur/hair/fabric/skin materials, warm cinematic feature-film lighting, natural shadows, polished global illumination, rich natural color, gentle depth of field, dimensional environments, clean shapes, refined storybook warmth. ONE rendering language for the whole movie. Never drift into photorealism, flat illustration, anime, 2D line art, plastic-toy rendering, or a different character-design style.`;
const CONTINUITY = `TV-EPISODE CONTINUITY: This is ONE continuous movie temporarily divided into generation shots. Write all 18 scenes as consecutive shots from the same episode, never 18 mini-films. Scene N+1 must begin from the physical/story state where Scene N ends. Carry forward the same subjects, established appearance, clothing/collars/accessories, proportions, location when the story remains there, props, time of day, emotional state and unfinished action. Do not reset, reintroduce, recap, teleport, redesign, or independently recast subjects between scenes. Each scene's videoPrompt must explicitly state its incoming continuity from the preceding scene and its outgoing action into the next scene.`;
const LANGUAGE = `LANGUAGE LOCK: English only by default. Every narration line and any spoken dialogue/singing containing words is natural English. Never introduce another language or infer language, nationality, ethnicity or accent from appearance, name, photograph, location or setting.`;
export async function POST(request: Request) {
  const { ownerId } = await getOwner(); const { premise, subjectPhotoPathnames = [], moods = [] } = await request.json();
  if (!Array.isArray(subjectPhotoPathnames) || !Array.isArray(moods) || typeof premise !== 'string') return NextResponse.json({ error: 'Photo references, mood, and story direction are required.' }, { status: 400 });
  if (subjectPhotoPathnames.length < 1 || subjectPhotoPathnames.length > 3) return NextResponse.json({ error: 'Upload one to three reference photos.' }, { status: 400 });
  if (subjectPhotoPathnames.some((pathname: unknown) => typeof pathname !== 'string' || !pathname.startsWith(`studio/owners/${ownerId}/references/`))) return NextResponse.json({ error: 'Photo references must belong to this preview.' }, { status: 403 });
  const customerCanon = premise.trim();
  const { object } = await generateObject({ model: 'openai/gpt-5.4', schema: storySchema, prompt: `Write one complete connected 3-minute animated movie in exactly 18 consecutive production shots. ${HOUSE_STYLE} ${CONTINUITY} ${LANGUAGE}
CUSTOMER CANON — HIGHEST PRIORITY SUBJECT FACTS: ${customerCanon || 'No extra typed subject facts; use the uploaded reference subject(s) as authoritative.'}
Anything the customer explicitly states about a subject—name, human/animal identity, species, breed/type, coat/hair/skin/eye color, markings, age presentation, clothing, relationship or other visible/identity detail—is CANON and must be repeated accurately in every relevant scene prompt. Never replace a specifically described subject with a generic character, different breed/species, different coloring, different human appearance or different number of subjects. The uploaded photos are authoritative visual references and supplement the customer's words. Do not infer ethnicity or nationality.
Mood: ${moods.join(', ') || 'family adventure'}. Follow the customer's requested story faithfully; when they leave the story blank, invent the plot while preserving the reference subjects exactly. Build a real beginning, escalating middle, climax and satisfying ending. Scenes 1-6 form the 1-minute free preview and are the actual opening of this same 3-minute movie; scenes 7-18 continue the already-planned episode after purchase. Every scene must advance the same plot with meaningful physical action, camera direction and concise English narration. Every videoPrompt must restate the canonical subject identity/details relevant to that shot plus the exact continuity handoff from the previous shot. Do not add scene labels.` });
  return NextResponse.json({ story: object });
}
